### PR TITLE
🔄 update README

### PR DESCRIPTION
**Pull request by idinium96**
@Preport please check if this is correct or not

### CODE REVIEW

**Comment by Preport** [comment]
On a side note applyStrangifier works with Unusualifiers as well that didn't came to my mind when I was naming the function.
You might want to rename it or rather create an alias up to you :3

**Comment by idinium96** [comment]
> On a side note applyStrangifier works with Unusualifiers as well that didn't came to my mind when I was naming the function.
> You might want to rename it or rather create an alias up to you :3

Ohh I see. Alright maybe just rename it to `applyStrangifierOrUnusualifier` 😏

**Comment by Preport** [comment]
Steam calls it applyXifier.
But that's probably confusing and hard to find.

**Comment by idinium96** [comment]
> Steam calls it applyXifier.
> But that's probably confusing and hard to find.

Noted. Yeah probably is, but that sounds simpler. well idk maybe just make it `applyStrangifierOrUnusualifier` :3

**Pull request merged**
